#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="parqueo")]
public partial class DBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertEnParqueo(EnParqueo instance);
  partial void UpdateEnParqueo(EnParqueo instance);
  partial void DeleteEnParqueo(EnParqueo instance);
  partial void InsertOperadore(Operadore instance);
  partial void UpdateOperadore(Operadore instance);
  partial void DeleteOperadore(Operadore instance);
  partial void InsertRegistro(Registro instance);
  partial void UpdateRegistro(Registro instance);
  partial void DeleteRegistro(Registro instance);
  #endregion
	
	public DBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["parqueoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<EnParqueo> EnParqueos
	{
		get
		{
			return this.GetTable<EnParqueo>();
		}
	}
	
	public System.Data.Linq.Table<Operadore> Operadores
	{
		get
		{
			return this.GetTable<Operadore>();
		}
	}
	
	public System.Data.Linq.Table<Registro> Registros
	{
		get
		{
			return this.GetTable<Registro>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EnParqueo")]
public partial class EnParqueo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idParqueo;
	
	private System.Nullable<int> _idRegistro;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidParqueoChanging(int value);
    partial void OnidParqueoChanged();
    partial void OnidRegistroChanging(System.Nullable<int> value);
    partial void OnidRegistroChanged();
    #endregion
	
	public EnParqueo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParqueo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idParqueo
	{
		get
		{
			return this._idParqueo;
		}
		set
		{
			if ((this._idParqueo != value))
			{
				this.OnidParqueoChanging(value);
				this.SendPropertyChanging();
				this._idParqueo = value;
				this.SendPropertyChanged("idParqueo");
				this.OnidParqueoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistro", DbType="Int")]
	public System.Nullable<int> idRegistro
	{
		get
		{
			return this._idRegistro;
		}
		set
		{
			if ((this._idRegistro != value))
			{
				this.OnidRegistroChanging(value);
				this.SendPropertyChanging();
				this._idRegistro = value;
				this.SendPropertyChanged("idRegistro");
				this.OnidRegistroChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Operadores")]
public partial class Operadore : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idOperador;
	
	private string _nombre;
	
	private string _apellidos;
	
	private string _usuario;
	
	private string _contraseña;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOperadorChanging(int value);
    partial void OnidOperadorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
	
	public Operadore()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOperador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idOperador
	{
		get
		{
			return this._idOperador;
		}
		set
		{
			if ((this._idOperador != value))
			{
				this.OnidOperadorChanging(value);
				this.SendPropertyChanging();
				this._idOperador = value;
				this.SendPropertyChanged("idOperador");
				this.OnidOperadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string apellidos
	{
		get
		{
			return this._apellidos;
		}
		set
		{
			if ((this._apellidos != value))
			{
				this.OnapellidosChanging(value);
				this.SendPropertyChanging();
				this._apellidos = value;
				this.SendPropertyChanged("apellidos");
				this.OnapellidosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this.OnusuarioChanging(value);
				this.SendPropertyChanging();
				this._usuario = value;
				this.SendPropertyChanged("usuario");
				this.OnusuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(50)")]
	public string contraseña
	{
		get
		{
			return this._contraseña;
		}
		set
		{
			if ((this._contraseña != value))
			{
				this.OncontraseñaChanging(value);
				this.SendPropertyChanging();
				this._contraseña = value;
				this.SendPropertyChanged("contraseña");
				this.OncontraseñaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registro")]
public partial class Registro : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idRegistro;
	
	private string _placa;
	
	private System.Nullable<System.DateTime> _fechaEntrada;
	
	private System.Nullable<System.DateTime> _fechaSalida;
	
	private System.Nullable<decimal> _tarifa;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRegistroChanging(int value);
    partial void OnidRegistroChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OnfechaEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntradaChanged();
    partial void OnfechaSalidaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaSalidaChanged();
    partial void OntarifaChanging(System.Nullable<decimal> value);
    partial void OntarifaChanged();
    #endregion
	
	public Registro()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idRegistro
	{
		get
		{
			return this._idRegistro;
		}
		set
		{
			if ((this._idRegistro != value))
			{
				this.OnidRegistroChanging(value);
				this.SendPropertyChanging();
				this._idRegistro = value;
				this.SendPropertyChanged("idRegistro");
				this.OnidRegistroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="NVarChar(25)")]
	public string placa
	{
		get
		{
			return this._placa;
		}
		set
		{
			if ((this._placa != value))
			{
				this.OnplacaChanging(value);
				this.SendPropertyChanging();
				this._placa = value;
				this.SendPropertyChanged("placa");
				this.OnplacaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntrada", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaEntrada
	{
		get
		{
			return this._fechaEntrada;
		}
		set
		{
			if ((this._fechaEntrada != value))
			{
				this.OnfechaEntradaChanging(value);
				this.SendPropertyChanging();
				this._fechaEntrada = value;
				this.SendPropertyChanged("fechaEntrada");
				this.OnfechaEntradaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalida", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaSalida
	{
		get
		{
			return this._fechaSalida;
		}
		set
		{
			if ((this._fechaSalida != value))
			{
				this.OnfechaSalidaChanging(value);
				this.SendPropertyChanging();
				this._fechaSalida = value;
				this.SendPropertyChanged("fechaSalida");
				this.OnfechaSalidaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarifa", DbType="Money")]
	public System.Nullable<decimal> tarifa
	{
		get
		{
			return this._tarifa;
		}
		set
		{
			if ((this._tarifa != value))
			{
				this.OntarifaChanging(value);
				this.SendPropertyChanging();
				this._tarifa = value;
				this.SendPropertyChanged("tarifa");
				this.OntarifaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
